locale                   : "fi-FI"
title                    : "Jani Suista / Web-Stack"
title_separator          : "-"
url                      : https://janisuista.github.io
repository               : "janisuista/janisuista.github.io"
breadcrumbs              : false
remote_theme             : pmarsceill/just-the-docs
